apiVersion: v1
kind: Secret
metadata:
  name: knowage-db-secret
  namespace: knowage
type: Opaque
data:
  db-user: a25vd2FnZQ== # knowage
  db-pass: a25vd2FnZQ== # knowage
  db-root-pass: cm9vdA== # root
  db-db: a25vd2FnZQ== # knowage
---
apiVersion: v1
kind: Secret
metadata:
  name: knowage-secret
  namespace: knowage
type: Opaque
data:
  hmac: Nk1kYzRmMjhpV1lQWDd6OWp5NVpyVFFvcTNidU52
  password-encryption-secret: eEI2a00yRG9VSlBWd05kYkt1NzM5NFRBR2FYODVMSA==
